version: 2.1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - run:
          name: Build Docker Image
          command: |
            docker build -t ci_demo .
      - run:
          name: Configure AWS access Key
          command: |
            aws configure set aws_access_key_id \
            $AWS_ACCESS_KEY_ID \
            --profile default
      - run:
          name: Configure AWS Secret Key
          command: |
            aws configure set aws_secret_access_key \
            $AWS_SECRET_ACCESS_KEY \
            --profile default
      - run:  
          name: Configure AWS Region
          command: |
            aws configure set region $AWS_REGION \
            --profile default
      - run:
          name: ECR Login
        command: >
        # aws ecr get-login returns a login command w/ a temp token

          LOGIN_COMMAND=$(aws ecr get-login --no-include-email --region
          $AWS_REGION --registry-ids $<<parameters.account-id>>
          --profile default
          $LOGIN_COMMAND
            
workflows:
  build-test:
    jobs:
      - build         
 
